dan-vernon/zeroplusone

Gemfile, Gemfile.lock, app/models/user.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20190225162412_devise_create_users.rb, db/schema.rb, test/models/user_test.rb
devise auto-generated user model,added extra user columns to migration, gemfile updated with omniauth gem
=> devise and user model created

app/models/booking.rb, db/migrate/20190225163116_add_ids_to_bookings.rb
corrected the issues with model
=> Create booking model

app/models/skill.rb, db/migrate/20190225170743_create_skills.rb, db/migrate/20190225174151_add_type_to_skill.rb, db/schema.rb, db/seeds.rb, test/models/skill_test.rb
=> Create skills model

app/models/booking.rb, app/models/user.rb, db/migrate/20190225162412_devise_create_users.rb, db/migrate/20190225162501_create_bookings.rb, db/migrate/20190225163116_add_ids_to_bookings.rb, db/schema.rb
multiple changes to models/migration files to fix issues with user/booking associations
=> fixed user/booking associations and reordered migrations

db/migrate/20190226104247_remove_type_from_skills.rb, db/schema.rb
removed type column from skills table
=> type removed from skills

app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb
1. devise generates generic views for registration and login functions - to be reviewed when we work on front-end
2. routes checked and match expectations
3. user controller CRUD methods are covered by devise auto-generated controllers so no need to create at this stage
=> generated devise views and verified routes

Gemfile.lock, app/models/booking.rb, app/models/review.rb, app/models/user.rb, db/migrate/20190226111946_create_reviews.rb, db/schema.rb, test/models/review_test.rb
created the review model, added validations and associations. Therefore added associations to bookings and user models.
=> Review model

Gemfile.lock, package.json, yarn.lock
ran security fix on webpack gem per barangerben instructions
=> webpack security fix

Gemfile, Gemfile.lock
pundit gem added to gem files, please do bundle after pulling
=> pundit gem added to gemfiles

app/controllers/users_controller.rb, app/views/users/index.html.erb, app/views/users/show.html.erb, config/routes.rb, test/controllers/users_controller_test.rb
created user controller with index and show methods
=> User controller

app/controllers/application_controller.rb, app/controllers/users_controller.rb, app/views/pages/home.html.erb, app/views/users/show.html.erb
Divise form for signup wasn't working. Fixed by adding configure_permitted_parameters to applications controller.   Users_controller show method commented due to error # @user_dob = helpers.age_in_years(@user). Log out link added to home page. User. show not complete, but working.
=> fixed devise form

Gemfile, Gemfile.lock, db/seeds.rb
created seed file for 50 users requiring faker gem. no seed of link to skill/skillset in this version
=> basic seed file

.gitignore, Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/models/user.rb, app/uploaders/photo_uploader.rb, app/views/devise/registrations/_signup_form.html.erb, config/application.rb, db/migrate/20190227115959_add_photo_to_users.rb, db/schema.rb
Added gems and UI for photo uploader
=> Photo uploader

app/views/layouts/application.html.erb, app/views/pages/home.html.erb
removed bg image, fixed cards inc link to user profile
=> Homepage styling

db/seeds.rb
photo random flickr image matching "hero" keyword
=> updated seeds.rb to include random user photo 

app/views/pages/home.html.erb
removed silly filter on hero cards / homepage
=> remove homepage hero card image filter 

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_navbar.scss, app/controllers/pages_controller.rb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/users/index.html.erb
css added to home page, sign up form deleted for now
=> home page css

app/views/layouts/application.html.erb
=> updated my bookings path

app/views/bookings/show.html.erb
=> edited display of booking info

app/views/pages/home.html.erb
code merged over in conflict error. add quotes around bg-image url for banner
=> reverted merge error 

app/models/user.rb, db/migrate/20190226111946_create_reviews.rb, db/schema.rb
- amended reviews migration file to fix plural error
- added reviews association to user model
can now call user.reviews and return all associated reviews for user
=> Reviews investigation

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/views/users/_show.html.erb, app/views/users/index.html.erb, app/views/users/show.html.erb
created partial for show and button in index. Abandoned ship on the modal dream.
=> Show partial

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_fonts.scss, app/assets/stylesheets/pages/_home.scss, app/views/layouts/application.html.erb, app/views/pages/home.html.erb
styling completed for home page, need to replace the placeholder video later
=> Re homepage styling

app/controllers/users_controller.rb, app/models/booking.rb, app/models/user.rb, config/routes.rb
review of bookings controller/model
- user bookings accessible as user.bookings_as_hero/zero
- user show controller exposes conditional display of user's bookings as @bookings instance variable
=> Bookings review

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_home.scss, app/views/pages/_navbar.html.erb, app/views/pages/home.html.erb
nav bar fixed, transparent for home page, purple for others
=> Landing update

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_home.scss
=> navbar margin changed

app/assets/stylesheets/pages/_devise-login.scss, app/assets/stylesheets/pages/_index.scss, app/views/devise/sessions/new.html.erb
show-folder class added to devise log in page. Top margin 100px added. Need to review button text colour once merged. showing black now.
=> devise login styling

app/assets/stylesheets/pages/_bookings-show.scss, app/views/devise/registrations/_signup_form.html.erb
show-holder class added to sign-up form. purple button added.
=> sign up form styling

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_bookings-new.scss, app/assets/stylesheets/pages/_index.scss, app/views/bookings/new.html.erb
Top margin added to bookings new page form. Bookings form class from user show page added for styling consistency. Purple nav bar padding issue fixed.
=> Bookings new

app/assets/stylesheets/pages/_bookings-show.scss, app/assets/stylesheets/pages/_index.scss, app/views/bookings/show.html.erb
show-holder class added to style the booking for the zero. Content styled. Top margin fixed
=> bookings show page styling

app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_user-signup.scss, app/views/devise/registrations/_signup_form.html.erb
background image added to signup form and styling completed
=> background image added

app/controllers/application_controller.rb, app/controllers/pages_controller.rb, app/controllers/users_controller.rb, app/views/layouts/application.html.erb, app/views/shared/_flashes.html.erb
devise authentication added to access any pages beyond home and main user index
=> Authentication

app/views/users/_show.html.erb
if / else statement added to profile view for current user
=> fixed buttons on profile view page

app/assets/stylesheets/pages/_bookings-index.scss, app/assets/stylesheets/pages/_bookings-show.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_user-signup.scss, app/views/bookings/index.html.erb, app/views/bookings/new.html.erb, app/views/bookings/show.html.erb, app/views/users/_show.html.erb, app/views/users/show.html.erb
background image added to pages
=> background image added to pages needed

app/views/bookings/show.html.erb
content edited and date format fixed
=> content styling fixed

app/assets/stylesheets/components/_cards.scss, app/controllers/bookings_controller.rb, app/views/bookings/index.html.erb, app/views/bookings/show.html.erb, app/views/pages/_navbar.html.erb
=> Last minute changes
